version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:  
    restart: always
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 1000:8080