version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hallo123
      POSTGRES_USER: job
    restart: always
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 1000:8080